# Generated by Django 4.2.2 on 2023-10-10 12:11

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.upload_avatar_path)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(related_name='+', through='profiles.Connection', to='profiles.profile', verbose_name='フォローされているユーザー')),
                ('followings', models.ManyToManyField(related_name='+', through='profiles.Connection', to='profiles.profile', verbose_name='フォロー中のユーザー')),
            ],
            options={
                'ordering': ['-created_on', '-updated_on'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_connection', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='connection',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_friendships', to='profiles.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('follower', 'following')},
        ),
    ]
